# Generated by Django 5.1.4 on 2024-12-16 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_shareholder_registration_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='share_amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Osa suurus peab olema vähemalt 1 euro.')], verbose_name='Osa suurus (EUR)'),
        ),
    ]
