# Generated by Django 5.1.4 on 2024-12-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_shareholder_share_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='personal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Isikukood'),
        ),
    ]
